import type {
  AgendaDay,
  ExperienceItem,
  FAQItem,
  NavigationItem,
  PricingPlan,
  Speaker,
  Sponsor,
  Testimonial,
} from '@/lib/types'

function avatar(name: string, background: string): string {
  return `https://ui-avatars.com/api/?name=${encodeURIComponent(name)}&size=512&background=${background}&color=ffffff&bold=true&format=png`
}

export const navigationItems: NavigationItem[] = [
  { id: 'nav-home', label: 'Home', href: '#home' },
  { id: 'nav-speakers', label: 'Speakers', href: '#speakers' },
  { id: 'nav-agenda', label: 'Agenda', href: '#agenda' },
  { id: 'nav-tickets', label: 'Tickets', href: '#tickets' },
  { id: 'nav-faq', label: 'FAQ', href: '#faq' },
  { id: 'nav-contact', label: 'Contact', href: '#contact' },
]

export const sponsors: Sponsor[] = [
  { id: 'openai', name: 'OpenAI' },
  { id: 'nvidia', name: 'NVIDIA' },
  { id: 'microsoft', name: 'Microsoft' },
  { id: 'google-cloud', name: 'Google Cloud' },
  { id: 'aws', name: 'AWS' },
  { id: 'anthropic', name: 'Anthropic' },
]

export const speakers: Speaker[] = [
  {
    id: 'andrew-ng',
    name: 'Andrew Ng',
    role: 'Founder',
    organization: 'DeepLearning.AI & AI Fund',
    topic: 'Keynote: The State of AI Education and Enterprise Adoption',
    initials: 'AN',
    gradient: 'from-blue-600 to-cyan-500',
    linkedin: 'https://www.linkedin.com/in/andrewyng',
    website: 'https://www.deeplearning.ai/',
    featured: true,
    image: avatar('Andrew Ng', '2563eb'),
  },
  {
    id: 'fei-fei-li',
    name: 'Fei-Fei Li',
    role: 'Founder · Professor at Stanford',
    organization: 'World Labs',
    topic: 'Spatial Intelligence and the Next Frontier of AI',
    initials: 'FL',
    gradient: 'from-purple-600 to-blue-500',
    linkedin: 'https://www.linkedin.com/in/fei-fei-li-4541247',
    website: 'https://www.worldlabs.ai/',
    featured: true,
    image: avatar('Fei-Fei Li', '7c3aed'),
  },
  {
    id: 'cassie-kozyrkov',
    name: 'Cassie Kozyrkov',
    role: 'AI & Decision Intelligence Speaker',
    organization: 'Independent',
    topic: 'Decision Intelligence: Making AI Actually Useful',
    initials: 'CK',
    gradient: 'from-fuchsia-600 to-purple-500',
    linkedin: 'https://www.linkedin.com/in/cassiekozyrkov',
    website: 'https://kozyrkov.medium.com/',
    featured: true,
    image: avatar('Cassie Kozyrkov', 'c026d3'),
  },
  {
    id: 'allie-k-miller',
    name: 'Allie K. Miller',
    role: 'AI Advisor',
    organization: 'Fortune 500 Companies',
    topic: 'Enterprise AI Strategy That Actually Ships',
    initials: 'AM',
    gradient: 'from-cyan-600 to-emerald-500',
    linkedin: 'https://www.linkedin.com/in/alliekmiller',
    website: 'https://www.alliekmiller.com/',
    featured: true,
    image: avatar('Allie Miller', '0891b2'),
  },
  {
    id: 'harrison-chase',
    name: 'Harrison Chase',
    role: 'CEO',
    organization: 'LangChain',
    topic: 'Building Reliable Agentic Applications with LLMs',
    initials: 'HC',
    gradient: 'from-indigo-600 to-purple-500',
    linkedin: 'https://www.linkedin.com/in/harrison-chase-3b6a6313',
    website: 'https://www.langchain.com/',
    featured: true,
    image: avatar('Harrison Chase', '4f46e5'),
  },
  {
    id: 'clem-delangue',
    name: 'Clem Delangue',
    role: 'CEO',
    organization: 'Hugging Face',
    topic: 'Open Source AI and the Community-Built Future',
    initials: 'CD',
    gradient: 'from-amber-500 to-orange-500',
    linkedin: 'https://www.linkedin.com/in/clementdelangue',
    website: 'https://huggingface.co/',
    featured: true,
    image: avatar('Clem Delangue', 'd97706'),
  },
  {
    id: 'aravind-srinivas',
    name: 'Aravind Srinivas',
    role: 'CEO',
    organization: 'Perplexity AI',
    topic: 'Reinventing Search in the Age of AI',
    initials: 'AS',
    gradient: 'from-sky-600 to-indigo-500',
    linkedin: 'https://www.linkedin.com/in/aravind-srinivas-16051987',
    website: 'https://www.perplexity.ai/',
    featured: true,
    image: avatar('Aravind Srinivas', '0284c7'),
  },
  {
    id: 'ali-ghodsi',
    name: 'Ali Ghodsi',
    role: 'CEO',
    organization: 'Databricks',
    topic: 'Data Intelligence at Enterprise Scale',
    initials: 'AG',
    gradient: 'from-rose-500 to-fuchsia-600',
    linkedin: 'https://www.linkedin.com/in/alighodsi',
    website: 'https://www.databricks.com/',
    featured: true,
    image: avatar('Ali Ghodsi', 'e11d48'),
  },
  {
    id: 'rajiv-parikh',
    name: 'Rajiv Parikh',
    role: 'Growth Marketing CEO',
    organization: 'GTM Community Builder',
    topic: 'Go-to-Market Playbooks for AI Products',
    initials: 'RP',
    gradient: 'from-emerald-600 to-cyan-500',
    linkedin: 'https://www.linkedin.com/in/rajivparikh/',
    website: 'https://www.linkedin.com/in/rajivparikh/',
    featured: true,
    image: avatar('Rajiv Parikh', '059669'),
  },
]

export const agendaDays: AgendaDay[] = [
  {
    id: 'day-1',
    label: 'Day 1',
    date: 'September 17',
    sessions: [
      { id: 'd1-1', time: '8:00 AM', title: 'Registration and Networking Breakfast', speakers: '', type: 'Networking' },
      { id: 'd1-2', time: '9:00 AM', title: 'Opening Keynote: The State of AI Education and Enterprise Adoption', speakers: 'Andrew Ng', type: 'Keynote' },
      { id: 'd1-3', time: '10:00 AM', title: 'Enterprise AI Strategy That Actually Ships', speakers: 'Allie K. Miller', type: 'Session' },
      { id: 'd1-4', time: '11:00 AM', title: 'Networking Break', speakers: '', type: 'Break' },
      { id: 'd1-5', time: '11:30 AM', title: 'Panel: From AI Experiments to Business Impact', speakers: 'Cassie Kozyrkov, Allie K. Miller, Ali Ghodsi', type: 'Panel' },
      { id: 'd1-6', time: '1:00 PM', title: 'Lunch and Startup Showcase', speakers: '', type: 'Showcase' },
      { id: 'd1-7', time: '2:00 PM', title: 'Building Reliable Agentic Applications with LLMs', speakers: 'Harrison Chase', type: 'Session' },
      { id: 'd1-8', time: '3:00 PM', title: 'Technical Workshop: Building Production-Ready RAG Systems', speakers: 'Harrison Chase', type: 'Workshop' },
      { id: 'd1-9', time: '4:30 PM', title: 'Decision Intelligence: Making AI Actually Useful', speakers: 'Cassie Kozyrkov', type: 'Session' },
      { id: 'd1-10', time: '6:00 PM', title: 'ARENA AI Summit Networking Reception', speakers: '', type: 'Networking' },
    ],
  },
  {
    id: 'day-2',
    label: 'Day 2',
    date: 'September 18',
    sessions: [
      { id: 'd2-1', time: '8:30 AM', title: 'Breakfast and Community Networking', speakers: '', type: 'Networking' },
      { id: 'd2-2', time: '9:30 AM', title: 'Keynote: Spatial Intelligence and the Next Frontier of AI', speakers: 'Fei-Fei Li', type: 'Keynote' },
      { id: 'd2-3', time: '10:30 AM', title: 'Open Source AI and the Community-Built Future', speakers: 'Clem Delangue', type: 'Session' },
      { id: 'd2-4', time: '11:30 AM', title: 'Networking Break', speakers: '', type: 'Break' },
      { id: 'd2-5', time: '12:00 PM', title: 'Data Intelligence at Enterprise Scale', speakers: 'Ali Ghodsi', type: 'Session' },
      { id: 'd2-6', time: '1:00 PM', title: 'Lunch', speakers: '', type: 'Break' },
      { id: 'd2-7', time: '2:00 PM', title: 'Reinventing Search in the Age of AI', speakers: 'Aravind Srinivas', type: 'Session' },
      { id: 'd2-8', time: '3:00 PM', title: 'Go-to-Market Playbooks for AI Products', speakers: 'Rajiv Parikh', type: 'Workshop' },
      { id: 'd2-9', time: '4:30 PM', title: 'Closing Panel: The Road Ahead for AI', speakers: 'Andrew Ng, Fei-Fei Li, Aravind Srinivas', type: 'Panel' },
      { id: 'd2-10', time: '5:30 PM', title: 'Closing Remarks and Community Meetup', speakers: '', type: 'Networking' },
    ],
  },
]

export const experienceItems: ExperienceItem[] = [
  { id: 'main-stage', title: 'Main Stage', description: 'Keynotes and headline panels from the leaders defining the AI landscape.', span: 'md:col-span-2', gradient: 'from-blue-600/30 to-purple-600/20' },
  { id: 'workshops', title: 'Technical Workshops', description: 'Hands-on, instructor-led sessions on RAG, agents, and production ML.', span: '', gradient: 'from-cyan-600/30 to-blue-600/20' },
  { id: 'showcase', title: 'Startup Showcase', description: 'Discover breakout AI startups demoing live on the expo floor.', span: '', gradient: 'from-fuchsia-600/30 to-purple-600/20' },
  { id: 'networking', title: 'Executive Networking', description: 'Curated roundtables and lounges for decision-makers and founders.', span: '', gradient: 'from-indigo-600/30 to-cyan-600/20' },
  { id: 'demos', title: 'AI Product Demonstrations', description: 'See the latest models, tools, and platforms in action across the venue.', span: '', gradient: 'from-emerald-600/30 to-cyan-600/20' },
  { id: 'investors', title: 'Investor Meetings', description: 'Structured meetings connecting founders with active AI investors and funds.', span: 'md:col-span-2', gradient: 'from-purple-600/30 to-rose-600/20' },
]

export const testimonials: Testimonial[] = [
  { id: 't-kavya', name: 'Kavya Srinivasan', role: 'Head of Data Science', company: 'FinEdge Analytics', quote: 'An exceptional mix of technical depth and strategic insight. I left with ideas we could immediately apply.', initials: 'KS' },
  { id: 't-marcus', name: 'Marcus Bell', role: 'Chief Technology Officer', company: 'Streamline Robotics', quote: 'The quality of conversations was outstanding. I met founders, researchers, and enterprise leaders in one place.', initials: 'MB' },
  { id: 't-ananya', name: 'Ananya Ghosh', role: 'Product Director', company: 'HelixWorks', quote: 'One of the few conferences where the technical sessions and executive discussions were equally valuable.', initials: 'AG' },
]

export const pricingPlans: PricingPlan[] = [
  {
    id: 'explorer',
    name: 'Explorer Pass',
    price: '₹9,999',
    popular: false,
    features: [
      'Access to both conference days',
      'Keynotes and panel sessions',
      'Exhibition and startup showcase',
      'Networking application',
      'Digital session recordings',
    ],
    cta: 'Choose Explorer',
  },
  {
    id: 'professional',
    name: 'Professional Pass',
    price: '₹19,999',
    popular: true,
    features: [
      'Everything in Explorer',
      'Technical workshops',
      'Reserved session seating',
      'Speaker meet-and-greet access',
      'Networking reception',
      'Certificate of participation',
    ],
    cta: 'Choose Professional',
  },
  {
    id: 'executive',
    name: 'Executive Pass',
    price: '₹39,999',
    popular: false,
    features: [
      'Everything in Professional',
      'Executive lounge access',
      'Private roundtable sessions',
      'Priority event check-in',
      'Investor and founder networking',
      'Premium dinner invitation',
    ],
    cta: 'Choose Executive',
  },
]

export const faqItems: FAQItem[] = [
  { id: 'faq-1', question: 'Who should attend ARENA AI Summit 2026?', answer: 'The summit is designed for AI researchers, engineers, founders, product leaders, investors, and enterprise decision-makers. Whether you are building AI systems, evaluating them for your organization, or investing in the ecosystem, the program includes dedicated tracks for both technical and strategic audiences.' },
  { id: 'faq-2', question: 'Where is the summit taking place?', answer: 'ARENA AI Summit 2026 takes place at the Bengaluru International Convention Centre in Bengaluru, India, on September 17–18, 2026. Detailed venue directions, parking information, and recommended accommodation will be shared with confirmed attendees.' },
  { id: 'faq-3', question: 'Are workshop sessions included with every ticket?', answer: 'Technical workshops are included with the Professional and Executive passes. Explorer Pass holders have full access to keynotes, panels, and the exhibition floor, and can upgrade to a workshop-inclusive pass at any time before the event, subject to availability.' },
  { id: 'faq-4', question: 'Will session recordings be available?', answer: 'Yes. All ticket tiers include digital recordings of keynotes and panel sessions, delivered within two weeks of the summit. Workshop recordings are available to Professional and Executive pass holders.' },
  { id: 'faq-5', question: 'Can I transfer my ticket to another person?', answer: 'Tickets can be transferred to a colleague free of charge up to 14 days before the event. Simply contact our team with the new attendee\u2019s details and we will reissue the registration.' },
  { id: 'faq-6', question: 'What is the refund policy?', answer: 'Full refunds are available up to 60 days before the event and 50% refunds up to 30 days before. Within 30 days of the event, tickets are non-refundable but remain transferable to another attendee free of charge up to 14 days before the event.' },
  { id: 'faq-7', question: 'Is the venue accessible?', answer: 'Yes. The Bengaluru International Convention Centre offers step-free access, accessible restrooms, elevators, and reserved seating in all session rooms. Live captioning is provided for keynotes, and quiet rooms are available on both days. Contact us in advance for specific accessibility arrangements.' },
]
