import type { Speaker } from '@/lib/types'

function avatar(name: string, background: string): string {
  return `https://ui-avatars.com/api/?name=${encodeURIComponent(name)}&size=256&background=${background}&color=ffffff&bold=true&format=png`
}

export const summitSpeakers: Speaker[] = [
  {
    id: 'andrew-ng',
    name: 'Andrew Ng',
    role: 'Founder',
    organization: 'DeepLearning.AI & AI Fund',
    topic: 'Keynote: The State of AI Education and Enterprise Adoption',
    initials: 'AN',
    gradient: 'from-blue-600 to-cyan-500',
    linkedin: 'https://www.linkedin.com/in/andrewyng',
    website: 'https://www.deeplearning.ai/',
    featured: true,
    image: avatar('Andrew Ng', '2563eb'),
  },
  {
    id: 'fei-fei-li',
    name: 'Fei-Fei Li',
    role: 'Founder · Professor at Stanford',
    organization: 'World Labs',
    topic: 'Spatial Intelligence and the Next Frontier of AI',
    initials: 'FL',
    gradient: 'from-purple-600 to-blue-500',
    linkedin: 'https://www.linkedin.com/in/fei-fei-li-4541247',
    website: 'https://www.worldlabs.ai/',
    featured: true,
    image: avatar('Fei-Fei Li', '7c3aed'),
  },
  {
    id: 'cassie-kozyrkov',
    name: 'Cassie Kozyrkov',
    role: 'AI & Decision Intelligence Speaker',
    organization: 'Independent',
    topic: 'Decision Intelligence: Making AI Actually Useful',
    initials: 'CK',
    gradient: 'from-fuchsia-600 to-purple-500',
    linkedin: 'https://www.linkedin.com/in/cassiekozyrkov',
    website: 'https://kozyrkov.medium.com/',
    featured: true,
    image: avatar('Cassie Kozyrkov', 'c026d3'),
  },
  {
    id: 'allie-k-miller',
    name: 'Allie K. Miller',
    role: 'AI Advisor',
    organization: 'Fortune 500 Companies',
    topic: 'Enterprise AI Strategy That Actually Ships',
    initials: 'AM',
    gradient: 'from-cyan-600 to-emerald-500',
    linkedin: 'https://www.linkedin.com/in/alliekmiller',
    website: 'https://www.alliekmiller.com/',
    featured: true,
    image: avatar('Allie Miller', '0891b2'),
  },
  {
    id: 'harrison-chase',
    name: 'Harrison Chase',
    role: 'CEO',
    organization: 'LangChain',
    topic: 'Building Reliable Agentic Applications with LLMs',
    initials: 'HC',
    gradient: 'from-indigo-600 to-purple-500',
    linkedin: 'https://www.linkedin.com/in/harrison-chase-3b6a6313',
    website: 'https://www.langchain.com/',
    featured: true,
    image: avatar('Harrison Chase', '4f46e5'),
  },
  {
    id: 'clem-delangue',
    name: 'Clem Delangue',
    role: 'CEO',
    organization: 'Hugging Face',
    topic: 'Open Source AI and the Community-Built Future',
    initials: 'CD',
    gradient: 'from-amber-500 to-orange-500',
    linkedin: 'https://www.linkedin.com/in/clementdelangue',
    website: 'https://huggingface.co/',
    featured: true,
    image: avatar('Clem Delangue', 'd97706'),
  },
  {
    id: 'aravind-srinivas',
    name: 'Aravind Srinivas',
    role: 'CEO',
    organization: 'Perplexity AI',
    topic: 'Reinventing Search in the Age of AI',
    initials: 'AS',
    gradient: 'from-sky-600 to-indigo-500',
    linkedin: 'https://www.linkedin.com/in/aravind-srinivas-16051987',
    website: 'https://www.perplexity.ai/',
    featured: true,
    image: avatar('Aravind Srinivas', '0284c7'),
  },
  {
    id: 'ali-ghodsi',
    name: 'Ali Ghodsi',
    role: 'CEO',
    organization: 'Databricks',
    topic: 'Data Intelligence at Enterprise Scale',
    initials: 'AG',
    gradient: 'from-rose-500 to-fuchsia-600',
    linkedin: 'https://www.linkedin.com/in/alighodsi',
    website: 'https://www.databricks.com/',
    featured: true,
    image: avatar('Ali Ghodsi', 'e11d48'),
  },
]
